### ISSUE TITLE
Function graph is empty, if functions are placed in separate Project

### ISSUE THREAD

**Issue by thomasvanveen** [scale-tone/az-func-as-a-graph#17]
Functions can be moved to a separate project if you add the following property to the function project file.
`<FunctionsInDependencies>true</FunctionsInDependencies>`. Unfortunatly those functions are not displayed in the graph.

**Comment by scale-tone** [comment]
It is indeed an issue for multi-assembly .NET projects like yours, @thomasvanveen .

For .NET In-Process Functions (which I assume is your case) we can partially address that by also taking function.json files into account.

But for the upcoming .NET Isolated, sadly, it would be much more complicated, because there isn't even such a thing as function.json there. So far, az-func-as-a-graph (since it is a javascript app) fully relies on the sources and cannot e.g. extract info from binaries via reflection magic. Will need to think more and maybe come up with some hybrid solution...
